version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db

  wpcli:
    image: wordpress:cli-2.7.1-php8.2
    entrypoint: ["wp"]
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html/web
    depends_on:
      - db

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html:ro
      - ./config/nginx/site.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  db:
    image: mariadb:10.9
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp_pass
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - db_data:/var/lib/mysql

  node:
    image: node:18-alpine
    working_dir: /var/www/html/web/app/themes/sage
    volumes:
      - ./web/app/themes/sage:/var/www/html/web/app/themes/sage
    command: ["npm","run","dev"]

volumes:
  db_data:
